apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: custom-nginx-proxy:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
