apiVersion: v1
kind: Pod
metadata:
  name: curl-client
  namespace: probe-lab
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:8.12.1
      command:
        - sleep
        - "3600"