apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task7-nginx.fullname" . }}
  labels:
    {{- include "task7-nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "task7-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "task7-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
