apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: task9
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:4.2.2
          args:
            - /fluent-bit/bin/fluent-bit
            - -c
            - /fluent-bit/etc/fluent-bit.conf
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: host-logs
              mountPath: /var/log/task9-nginx
              readOnly: true
            - name: state
              mountPath: /fluent-bit/state
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config
        - name: host-logs
          hostPath:
            path: /var/log/task9-nginx
            type: DirectoryOrCreate
        - name: state
          emptyDir: {}
