fullnameOverride: grafana

adminUser: admin

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false

testFramework:
  enabled: false

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.task9.svc.cluster.local
        isDefault: true
        editable: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
