apiVersion: v1
kind: ConfigMap
metadata:
  name: task9-nginx-config
  namespace: task9
data:
  nginx.conf: |
    events {}
    http {
      access_log /var/log/nginx/access.log combined;
      error_log /var/log/nginx/error.log warn;

      server {
        listen 80;
        server_name _;

        location / {
          add_header Content-Type text/plain;
          return 200 "task9 nginx log demo\n";
        }
      }
    }
