apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task6-platform.nginxConfigName" . }}
  labels:
    {{- include "task6-platform.labels" . | nindent 4 }}
data:
  default.conf: |
    upstream web_backend {
        server {{ include "task6-platform.webServiceName" . }}:{{ .Values.web.service.port }};
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            add_header X-Proxy-Layer task6-nginx always;
            proxy_pass http://web_backend;
        }
    }
