apiVersion: v1
kind: Service
metadata:
  name: {{ include "task6-platform.redisHeadlessServiceName" . }}
  labels:
    {{- include "task6-platform.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "task6-platform.redisServiceName" . }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
