apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "task6-platform.redisServiceName" . }}
  labels:
    {{- include "task6-platform.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "task6-platform.redisHeadlessServiceName" . }}
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "task6-platform.redisServiceName" . }}
  template:
    metadata:
      labels:
        app: {{ include "task6-platform.redisServiceName" . }}
        {{- include "task6-platform.labels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - sh
            - -c
            - exec redis-server --appendonly yes --save 60 1 --requirepass "$REDIS_PASSWORD" --bind 0.0.0.0 --protected-mode no
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "task6-platform.redisAuthSecretName" . }}
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-data
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
