apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task6-platform.redisAuthSecretName" . }}
  labels:
    {{- include "task6-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_HOST: {{ include "task6-platform.redisTargetHost" . }}
  REDIS_PORT: "6379"
  REDIS_USERNAME: {{ .Values.redis.auth.username | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
