apiVersion: v1
kind: Service
metadata:
  name: {{ include "task6-platform.webServiceName" . }}
  labels:
    {{- include "task6-platform.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "task6-platform.webServiceName" . }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
