apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: week2-task6
type: Opaque
stringData:
  REDIS_HOST: redis-0.redis-headless.week2-task6.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_USERNAME: default
  REDIS_PASSWORD: task6-redis-pass
