fullnameOverride: grafana

adminUser: admin

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false

testFramework:
  enabled: false

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
